Locking down gopkg.in/src-d/go-git.v4 to < 4.7.1
To avoid compilation issues
```
github.com/sky-uk/licence-compliance-checker/vendor/gopkg.in/src-d/go-license-detector.v2/licensedb/filer
vendor/gopkg.in/src-d/go-license-detector.v2/licensedb/filer/filer.go:212:19:
cannot assign 1 values to 2 variables
vendor/gopkg.in/src-d/go-license-detector.v2/licensedb/filer/filer.go:212:43:
not enough arguments in call to filesystem.NewStorage
        have (sivafs.SivaFS)
        want (billy.Filesystem, cache.Object)
```

As `4.7.1` introduced a change in
https://github.com/src-d/go-git/commit/8f6b3127c1ff7661113fff2662416c328971a285
which is not backwark compatible as it changes the `filesystem.NewStorage` method signature.

Use version above 4.1.0 to accommodate the `go-licence-detector`
requirement as per the Gopkg.toml.